### ISSUE TITLE
[Feat][UI] Coming Soon Page

### ISSUE THREAD

**Issue by davidlhw** [AfterClass-io/afterclass.io-v2#84]
## Mockups / Screenshots

![image](https://github.com/AfterClass-io/afterclass.io-v2/assets/13061926/712e91a1-0a6d-4de0-a2ea-d97d6abb022d)

## TODO

possible avenue for improvements:

- [ ] extract the Coming Soon card as a separate component (should accept Title, Subtitle, and color/class as props)
- [ ] use bg-bg-elevated instead of just bg-white for the colours for theming support
- [ ] use h-full instead of h-screen to prevent overscrolling
